# have not tested this yet
version: '3.8'
services:
  influxdb:
    image: influxdb:2.7.4
    container_name: influxdb
    volumes:
      - influxdb2:/var/lib/influxdb2
    ports:
      - "8086:8086"
volumes:
  influxdb2:
