"""Add container model

Revision ID: 27d71ff4b11b
Revises: 671416d5bcda
Create Date: 2023-12-02 22:52:34.530222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d71ff4b11b'
down_revision: Union[str, None] = '671416d5bcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_status',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('container_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('running_for', sa.String(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('full_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['container_name'], ['bots.container_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_status')
    # ### end Alembic commands ###
