"""Modify bot model

Revision ID: 6739d14ee03a
Revises: 6123015bc9a5
Create Date: 2023-11-30 16:28:03.483306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6739d14ee03a'
down_revision: Union[str, None] = '6123015bc9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('t_frame', sa.String(), nullable=False))
    op.add_column('bots', sa.Column('quantity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'quantity')
    op.drop_column('bots', 't_frame')
    # ### end Alembic commands ###
