version: '3.8'
services:
  influxdb:
    image: influxdb:2.7.4
    container_name: influxdb
    volumes:
      - influxdb2:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}

  worker:
    build: .
    container_name: mark-price-worker
    depends_on:
      - influxdb
    environment:
      - INFLUX_CONFIG_PATH=${INFLUX_CONFIG_PATH}
volumes:
  influxdb2:
